---
abstract: 'cooperative pandemic board game'
author:
  - 'Jerome Quelin'
generated_by: 'Dist::Zilla::Plugin::MetaYAML version 1.092450'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Games-Pandemic
provides:
  Games::Pandemic:
    file: lib/Games/Pandemic.pm
    version: 1.092640
  Games::Pandemic::Card:
    file: lib/Games/Pandemic/Card.pm
    version: 1.092640
  Games::Pandemic::Card::City:
    file: lib/Games/Pandemic/Card/City.pm
    version: 1.092640
  Games::Pandemic::Card::Epidemic:
    file: lib/Games/Pandemic/Card/Epidemic.pm
    version: 1.092640
  Games::Pandemic::Card::Special:
    file: lib/Games/Pandemic/Card/Special.pm
    version: 1.092640
  Games::Pandemic::Card::Special::Airlift:
    file: lib/Games/Pandemic/Card/Special/Airlift.pm
    version: 1.092640
  Games::Pandemic::Card::Special::Forecast:
    file: lib/Games/Pandemic/Card/Special/Forecast.pm
    version: 1.092640
  Games::Pandemic::Card::Special::GovernmentGrant:
    file: lib/Games/Pandemic/Card/Special/GovernmentGrant.pm
    version: 1.092640
  Games::Pandemic::Card::Special::OneQuietNight:
    file: lib/Games/Pandemic/Card/Special/OneQuietNight.pm
    version: 1.092640
  Games::Pandemic::Card::Special::ResilientPopulation:
    file: lib/Games/Pandemic/Card/Special/ResilientPopulation.pm
    version: 1.092640
  Games::Pandemic::City:
    file: lib/Games/Pandemic/City.pm
    version: 1.092640
  Games::Pandemic::Config:
    file: lib/Games/Pandemic/Config.pm
    version: 1.092640
  Games::Pandemic::Controller:
    file: lib/Games/Pandemic/Controller.pm
    version: 1.092640
  Games::Pandemic::Deck:
    file: lib/Games/Pandemic/Deck.pm
    version: 1.092640
  Games::Pandemic::Disease:
    file: lib/Games/Pandemic/Disease.pm
    version: 1.092640
  Games::Pandemic::Map:
    file: lib/Games/Pandemic/Map.pm
    version: 1.092640
  Games::Pandemic::Map::Pandemic:
    file: lib/Games/Pandemic/Map/Pandemic.pm
    version: 1.092640
  Games::Pandemic::Player:
    file: lib/Games/Pandemic/Player.pm
    version: 1.092640
  Games::Pandemic::Role::Dispatcher:
    file: lib/Games/Pandemic/Role/Dispatcher.pm
    version: 1.092640
  Games::Pandemic::Role::Medic:
    file: lib/Games/Pandemic/Role/Medic.pm
    version: 1.092640
  Games::Pandemic::Role::OperationsExpert:
    file: lib/Games/Pandemic/Role/OperationsExpert.pm
    version: 1.092640
  Games::Pandemic::Role::Researcher:
    file: lib/Games/Pandemic/Role/Researcher.pm
    version: 1.092640
  Games::Pandemic::Role::Scientist:
    file: lib/Games/Pandemic/Role/Scientist.pm
    version: 1.092640
  Games::Pandemic::Tk::Action:
    file: lib/Games/Pandemic/Tk/Action.pm
    version: 1.092640
  Games::Pandemic::Tk::Dialog:
    file: lib/Games/Pandemic/Tk/Dialog.pm
    version: 1.092640
  Games::Pandemic::Tk::Dialog::Action:
    file: lib/Games/Pandemic/Tk/Dialog/Action.pm
    version: 1.092640
  Games::Pandemic::Tk::Dialog::Airlift:
    file: lib/Games/Pandemic/Tk/Dialog/Airlift.pm
    version: 1.092640
  Games::Pandemic::Tk::Dialog::ChooseDisease:
    file: lib/Games/Pandemic/Tk/Dialog/ChooseDisease.pm
    version: 1.092640
  Games::Pandemic::Tk::Dialog::DropCards:
    file: lib/Games/Pandemic/Tk/Dialog/DropCards.pm
    version: 1.092640
  Games::Pandemic::Tk::Dialog::Forecast:
    file: lib/Games/Pandemic/Tk/Dialog/Forecast.pm
    version: 1.092640
  Games::Pandemic::Tk::Dialog::GiveCard:
    file: lib/Games/Pandemic/Tk/Dialog/GiveCard.pm
    version: 1.092640
  Games::Pandemic::Tk::Dialog::GovernmentGrant:
    file: lib/Games/Pandemic/Tk/Dialog/GovernmentGrant.pm
    version: 1.092640
  Games::Pandemic::Tk::Dialog::ResilientPopulation:
    file: lib/Games/Pandemic/Tk/Dialog/ResilientPopulation.pm
    version: 1.092640
  Games::Pandemic::Tk::Dialog::Simple:
    file: lib/Games/Pandemic/Tk/Dialog/Simple.pm
    version: 1.092640
  Games::Pandemic::Tk::Dialog::ViewCards:
    file: lib/Games/Pandemic/Tk/Dialog/ViewCards.pm
    version: 1.092640
  Games::Pandemic::Tk::Main:
    file: lib/Games/Pandemic/Tk/Main.pm
    version: 1.092640
  Games::Pandemic::Tk::PlayerCards:
    file: lib/Games/Pandemic/Tk/PlayerCards.pm
    version: 1.092640
  Games::Pandemic::Tk::Utils:
    file: lib/Games/Pandemic/Tk/Utils.pm
    version: 1.092640
  Games::Pandemic::Utils:
    file: lib/Games/Pandemic/Utils.pm
    version: 1.092640
requires:
  Convert::Color: 0
  Cwd: 0
  Devel::CheckOS: 0
  Encode: 0
  English: 0
  Exporter: 0
  ExtUtils::MakeMaker: 0
  File::Basename: 0
  File::Find: 0
  File::Find::Rule: 0
  File::HomeDir: 0
  File::Spec::Functions: 0
  FindBin: 0
  Geo::Mercator: 0
  Image::Size: 0
  List::MoreUtils: 0
  List::Util: 0
  Locale::TextDomain: 0
  Math::Gradient: 0
  Module::Util: 0
  Moose: 0
  Moose::Role: 0
  MooseX::AttributeHelpers: 0
  MooseX::POE: 0
  MooseX::SemiAffordanceAccessor: 0
  MooseX::Singleton: 0
  MooseX::Traits: 0
  POE: 0
  POE::Kernel: 0
  Readonly: 0
  Test::More: 0
  Tk: 0
  Tk::Balloon: 0
  Tk::Font: 0
  Tk::JPEG: 0
  Tk::PNG: 0
  Tk::Pane: 0
  Tk::Tiler: 0
  Tk::ToolBar: 0
  UNIVERSAL::require: 0
  YAML::Tiny: 0
  perl: 5.010
resources:
  homepage: http://search.cpan.org/dist/Games-Pandemic
  repository: http://github.com/jquelin/games-pandemic
version: 1.092640
