---
abstract: 'cooperative pandemic board game'
author:
  - 'Jerome Quelin'
generated_by: 'Dist::Zilla::Plugin::MetaYAML version '
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Games-Pandemic
requires:
  Cwd: 0
  Devel::CheckOS: 0
  Encode: 0
  Exporter: 0
  File::Basename: 0
  File::Find::Rule: 0
  File::HomeDir: 0
  File::Spec::Functions: 0
  FindBin: 0
  Geo::Mercator: 0
  Image::Size: 0
  List::MoreUtils: 0
  List::Util: 0
  Locale::TextDomain: 0
  Module::Util: 0
  Moose: 0
  Moose::Role: 0
  MooseX::AttributeHelpers: 0
  MooseX::POE: 0
  MooseX::SemiAffordanceAccessor: 0
  MooseX::Singleton: 0
  MooseX::Traits: 0
  POE: 0
  POE::Kernel: 0
  Readonly: 0
  Test::More: 0
  Tk: 0
  Tk::Font: 0
  Tk::JPEG: 0
  Tk::PNG: 0
  Tk::Pane: 0
  Tk::ToolBar: 0
  UNIVERSAL::require: 0
  YAML::Tiny: 0
  perl: 5.010
resources:
  homepage: http://search.cpan.org/dist/Games-Pandemic
  repository: http://github.com/jquelin/games-pandemic/
version: 0.6.0
